# Generated by Django 3.0.2 on 2020-01-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='უნარი')),
                ('progress', models.IntegerField(default=0, verbose_name='დონე')),
            ],
        ),
    ]
