# Generated by Django 3.0.2 on 2020-01-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200128_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
