# Generated by Django 3.0.2 on 2020-01-30 20:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\datoq_000\\Desktop\\ProjectProject/app/static/img/'), upload_to='')),
            ],
        ),
    ]
