# Generated by Django 3.0.2 on 2020-01-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200131_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
