# Generated by Django 3.0.2 on 2020-01-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
