# Generated by Django 3.0.2 on 2020-02-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
