# Generated by Django 3.0.2 on 2020-02-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='last_name_en',
            new_name='last_name_ge',
        ),
    ]
