# Generated by Django 3.0.2 on 2020-02-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_progress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progress',
            new_name='Projects',
        ),
    ]
