# Generated by Django 3.0.2 on 2020-02-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200203_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
