# Generated by Django 3.0.2 on 2020-02-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='used_technologies',
            field=models.TextField(help_text='<b>write technologie names like : <i>HTML | CSS | Java | JavaScript</i>...</b>', max_length=1000),
        ),
    ]
