# Generated by Django 3.0.2 on 2020-02-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200203_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='used_technologies',
        ),
    ]
