# Generated by Django 3.0.2 on 2020-02-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200203_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
